export enum AppAction {
    DISPATCH_DEVICE_RESOLUTION = 'DISPATCH_DEVICE_RESOLUTION',
    DISPATCH_TRANSLATIONS = 'DISPATCH_TRANSLATIONS',
    UPDATE_DEVICE = 'UPDATE_DEVICE',
    UPDATE_TRANSLATIONS = 'UPDATE_TRANSLATIONS',
}

export type ActionEnum = AppAction